apiVersion: apps/v1
kind: Deployment
metadata:
  name: swag-reverse-proxy
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: swag-reverse-proxy
  template:
    metadata:
      labels:
        app: swag-reverse-proxy
    spec:
      containers:
      - name: swag
        image: linuxserver/swag:latest
        ports:
        - containerPort: 443  # Adjust the port as needed
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "0002"
        - name: TZ
          value: "America/New_York"
        - name: URL
          value: "balbresky.vip"
        - name: SUBDOMAINS
          value: "wildcard"
        - name: VALIDATION
          value: "dns"
        - name: DNSPLUGIN
          value: "cloudflare"
        - name: EMAIL
          value: "imb8556@proton.me"
        - name: ONLY_SUBDOMAINS
          value: "false"
        - name: STAGING
          value: "false"
        # Add environment variables for SWAG configuration (e.g., domain name, email, etc.)
        # See SWAG documentation for available options
---
apiVersion: v1
kind: Service
metadata:
  name: swag-reverse-proxy
spec:
  selector:
    app: swag-reverse-proxy
  ports:
    - protocol: TCP
      port: 443  # Adjust the port as needed
      targetPort: 443